services:
  bibbloard:
    image: ghcr.io/abogatskiy/bibbloard:latest
    container_name: bibbloard
    restart: unless-stopped
    networks:
      - nginx_proxy-network

networks:
  nginx_proxy-network:
    external: true
